VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
LTO_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = yes

SIMPLE_CU7_LAYER_RGB = no

RGB_MATRIX_CUSTOM_USER = yes
